package br.inatel.fetin.fetindoctor.entity;

// Generated 14/09/2015 20:44:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Clinic generated by hbm2java
 */
@Entity
@Table(name = "clinic", catalog = "telit_user_side")
public class Clinic implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String district;
	private String city;
	private String state;
	private String phone;
	private String cnpj;
	private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

	public Clinic() {
	}

	public Clinic(String name, String address, String district, String city,
			String state, String phone, String cnpj) {
		this.name = name;
		this.address = address;
		this.district = district;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.cnpj = cnpj;
	}

	public Clinic(String name, String address, String district, String city,
			String state, String phone, String cnpj,
			Set<Prescription> prescriptions) {
		this.name = name;
		this.address = address;
		this.district = district;
		this.city = city;
		this.state = state;
		this.phone = phone;
		this.cnpj = cnpj;
		this.prescriptions = prescriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "district", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "city", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "phone", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "cnpj", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clinic")
	public Set<Prescription> getPrescriptions() {
		return this.prescriptions;
	}

	public void setPrescriptions(Set<Prescription> prescriptions) {
		this.prescriptions = prescriptions;
	}

}
