package br.inatel.fetin.fetindoctor.entity;

// Generated 14/09/2015 20:44:26 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "telit_user_side")
public class Doctor implements java.io.Serializable {

	private Integer id;
	private String name;
	private String crm;
	private String speciality;
	private String cpf;
	private String phone;
	private String cellphone;
	private String email;
	private Boolean enable;
	private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

	public Doctor() {
	}

	public Doctor(String name, String crm, String speciality, String cpf) {
		this.name = name;
		this.crm = crm;
		this.speciality = speciality;
		this.cpf = cpf;
	}

	public Doctor(String name, String crm, String speciality, String cpf,
			String phone, String cellphone, String email, Boolean enable,
			Set<Prescription> prescriptions) {
		this.name = name;
		this.crm = crm;
		this.speciality = speciality;
		this.cpf = cpf;
		this.phone = phone;
		this.cellphone = cellphone;
		this.email = email;
		this.enable = enable;
		this.prescriptions = prescriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "crm", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getCrm() {
		return this.crm;
	}

	public void setCrm(String crm) {
		this.crm = crm;
	}

	@Column(name = "speciality", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getSpeciality() {
		return this.speciality;
	}

	public void setSpeciality(String speciality) {
		this.speciality = speciality;
	}

	@Column(name = "cpf", nullable = false, length = 14)
	@NotNull
	@Length(max = 14)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "phone", length = 45)
	@Length(max = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "cellphone", length = 45)
	@Length(max = 45)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "email", length = 45)
	@Length(max = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "enable")
	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Prescription> getPrescriptions() {
		return this.prescriptions;
	}

	public void setPrescriptions(Set<Prescription> prescriptions) {
		this.prescriptions = prescriptions;
	}

}
