package br.inatel.fetin.fetindoctor.entity;

// Generated 14/09/2015 20:44:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * TreatmentHour generated by hbm2java
 */
@Entity
@Table(name = "treatment_hour", catalog = "telit_user_side")
public class TreatmentHour implements java.io.Serializable {

	private int id;
	private PrescriptionRemedy prescriptionRemedy;
	private Date treatmentHour;

	public TreatmentHour() {
	}

	public TreatmentHour(int id, PrescriptionRemedy prescriptionRemedy) {
		this.id = id;
		this.prescriptionRemedy = prescriptionRemedy;
	}

	public TreatmentHour(int id, PrescriptionRemedy prescriptionRemedy,
			Date treatmentHour) {
		this.id = id;
		this.prescriptionRemedy = prescriptionRemedy;
		this.treatmentHour = treatmentHour;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "prescription_remedy_pk_prescription_remedy", referencedColumnName = "id", nullable = false),
			@JoinColumn(name = "prescription_remedy_prescription_id", referencedColumnName = "prescription_id", nullable = false),
			@JoinColumn(name = "prescription_remedy_remedy_id", referencedColumnName = "remedy_id", nullable = false) })
	@NotNull
	public PrescriptionRemedy getPrescriptionRemedy() {
		return this.prescriptionRemedy;
	}

	public void setPrescriptionRemedy(PrescriptionRemedy prescriptionRemedy) {
		this.prescriptionRemedy = prescriptionRemedy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "treatment_hour", length = 8)
	public Date getTreatmentHour() {
		return this.treatmentHour;
	}

	public void setTreatmentHour(Date treatmentHour) {
		this.treatmentHour = treatmentHour;
	}

}
