package org.domain.egg2.entity;
// Generated 16/05/2019 18:26:57 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Expedition generated by hbm2java
 */
@Entity
@Table(name = "expedition", catalog = "db_egg_2")
public class Expedition implements java.io.Serializable {

	private int id;
	private Line line;
	private Date date;
	private Set<Production> productions = new HashSet<Production>(0);

	public Expedition() {
	}

	public Expedition(int id, Line line, Date date) {
		this.id = id;
		this.line = line;
		this.date = date;
	}

	public Expedition(int id, Line line, Date date, Set<Production> productions) {
		this.id = id;
		this.line = line;
		this.date = date;
		this.productions = productions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "line_id", nullable = false)
	@NotNull
	public Line getLine() {
		return this.line;
	}

	public void setLine(Line line) {
		this.line = line;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	@NotNull
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "expedition_has_production", catalog = "db_egg_2", joinColumns = {
			@JoinColumn(name = "expedition_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "production_id", nullable = false, updatable = false) })
	public Set<Production> getProductions() {
		return this.productions;
	}

	public void setProductions(Set<Production> productions) {
		this.productions = productions;
	}

}
