package org.domain.egg2.entity;
// Generated 16/05/2019 18:26:57 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ProductionProduct generated by hbm2java
 */
@Entity
@Table(name = "production_product", catalog = "db_egg_2")
public class ProductionProduct implements java.io.Serializable {

	private ProductionProductId id;
	private Product product;
	private Production production;
	private int quantityProduction;
	private int quantityBalance;

	public ProductionProduct() {
	}

	public ProductionProduct(ProductionProductId id, Product product, Production production, int quantityProduction,
			int quantityBalance) {
		this.id = id;
		this.product = product;
		this.production = production;
		this.quantityProduction = quantityProduction;
		this.quantityBalance = quantityBalance;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productionId", column = @Column(name = "production_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	@NotNull
	public ProductionProductId getId() {
		return this.id;
	}

	public void setId(ProductionProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "production_id", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Production getProduction() {
		return this.production;
	}

	public void setProduction(Production production) {
		this.production = production;
	}

	@Column(name = "quantity_production", nullable = false)
	public int getQuantityProduction() {
		return this.quantityProduction;
	}

	public void setQuantityProduction(int quantityProduction) {
		this.quantityProduction = quantityProduction;
	}

	@Column(name = "quantity_balance", nullable = false)
	public int getQuantityBalance() {
		return this.quantityBalance;
	}

	public void setQuantityBalance(int quantityBalance) {
		this.quantityBalance = quantityBalance;
	}

}
