package org.domain.egg2.entity;
// Generated 16/05/2019 18:26:57 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductionProductId generated by hbm2java
 */
@Embeddable
public class ProductionProductId implements java.io.Serializable {

	private int productionId;
	private int productId;
	private int id;

	public ProductionProductId() {
	}

	public ProductionProductId(int productionId, int productId, int id) {
		this.productionId = productionId;
		this.productId = productId;
		this.id = id;
	}

	@Column(name = "production_id", nullable = false)
	public int getProductionId() {
		return this.productionId;
	}

	public void setProductionId(int productionId) {
		this.productionId = productionId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductionProductId))
			return false;
		ProductionProductId castOther = (ProductionProductId) other;

		return (this.getProductionId() == castOther.getProductionId())
				&& (this.getProductId() == castOther.getProductId()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductionId();
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getId();
		return result;
	}

}
