package org.domain.egg2.entity;
// Generated 16/05/2019 18:26:57 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "db_egg_2")
public class Type implements java.io.Serializable {

	private int id;
	private String type;
	private int weight;
	private Set<Product> products = new HashSet<Product>(0);

	public Type() {
	}

	public Type(int id, String type, int weight) {
		this.id = id;
		this.type = type;
		this.weight = weight;
	}

	public Type(int id, String type, int weight, Set<Product> products) {
		this.id = id;
		this.type = type;
		this.weight = weight;
		this.products = products;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
