package br.com.eggerp.entity;
// Generated 24/05/2019 13:05:07 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Lineage generated by hbm2java
 */
@Entity
@Table(name = "lineage", catalog = "db_egg")
public class Lineage implements java.io.Serializable {

	private Integer id;
	private String lineage;
	private String color;
	private Set<Lot> lots = new HashSet<Lot>(0);

	public Lineage() {
	}

	public Lineage(String lineage) {
		this.lineage = lineage;
	}

	public Lineage(String lineage, String color, Set<Lot> lots) {
		this.lineage = lineage;
		this.color = color;
		this.lots = lots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lineage", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getLineage() {
		return this.lineage;
	}

	public void setLineage(String lineage) {
		this.lineage = lineage;
	}

	@Column(name = "color", length = 45)
	@Length(max = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lineage")
	public Set<Lot> getLots() {
		return this.lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

}
