package br.com.eggerp.entity;
// Generated 26/05/2019 21:21:09 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Line generated by hbm2java
 */
@Entity
@Table(name = "line", catalog = "db_egg")
public class Line implements java.io.Serializable {

	private int id;
	private String line;
	private String cities;
	private Set<Expedition> expeditions = new HashSet<Expedition>(0);

	public Line() {
	}

	public Line(int id, String line, String cities) {
		this.id = id;
		this.line = line;
		this.cities = cities;
	}

	public Line(int id, String line, String cities, Set<Expedition> expeditions) {
		this.id = id;
		this.line = line;
		this.cities = cities;
		this.expeditions = expeditions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "line", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "cities", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getCities() {
		return this.cities;
	}

	public void setCities(String cities) {
		this.cities = cities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "line")
	public Set<Expedition> getExpeditions() {
		return this.expeditions;
	}

	public void setExpeditions(Set<Expedition> expeditions) {
		this.expeditions = expeditions;
	}

}
