package br.com.eggerp.entity;
// Generated 24/05/2019 13:05:07 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Shed generated by hbm2java
 */
@Entity
@Table(name = "shed", catalog = "db_egg")
public class Shed implements java.io.Serializable {

	private Integer id;
	private Manufacturer manufacturer;
	private String name;
	private String type;
	private int capacity;
	private String model;
	private Set<Lot> lots = new HashSet<Lot>(0);

	public Shed() {
	}

	public Shed(Manufacturer manufacturer, String name, String type, int capacity) {
		this.manufacturer = manufacturer;
		this.name = name;
		this.type = type;
		this.capacity = capacity;
	}

	public Shed(Manufacturer manufacturer, String name, String type, int capacity, String model, Set<Lot> lots) {
		this.manufacturer = manufacturer;
		this.name = name;
		this.type = type;
		this.capacity = capacity;
		this.model = model;
		this.lots = lots;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manufacturer_id", nullable = false)
	@NotNull
	public Manufacturer getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(Manufacturer manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "name", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@Column(name = "model", length = 45)
	@Length(max = 45)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shed")
	public Set<Lot> getLots() {
		return this.lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

}
