package br.com.eggerp.entity;
// Generated 26/05/2019 21:21:09 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "db_egg")
public class Type implements java.io.Serializable {

	private int id;
	private String type;
	private int minimumWeight;
	private int maximumWeight;
	private Set<Product> products = new HashSet<Product>(0);

	public Type() {
	}

	public Type(int id, String type, int minimumWeight, int maximumWeight) {
		this.id = id;
		this.type = type;
		this.minimumWeight = minimumWeight;
		this.maximumWeight = maximumWeight;
	}

	public Type(int id, String type, int minimumWeight, int maximumWeight, Set<Product> products) {
		this.id = id;
		this.type = type;
		this.minimumWeight = minimumWeight;
		this.maximumWeight = maximumWeight;
		this.products = products;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "minimum_weight", nullable = false)
	public int getMinimumWeight() {
		return this.minimumWeight;
	}

	public void setMinimumWeight(int minimumWeight) {
		this.minimumWeight = minimumWeight;
	}

	@Column(name = "maximum_weight", nullable = false)
	public int getMaximumWeight() {
		return this.maximumWeight;
	}

	public void setMaximumWeight(int maximumWeight) {
		this.maximumWeight = maximumWeight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
